2018-02-21T11:02:39.503Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'nestle@email.com' as the object already exists)
    at /home/ibm/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-21T11:02:39.504Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'nestle@email.com' as the object already exists)","stack":"Error: Error trying invoke business network. Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'nestle@email.com' as the object already exists)\n    at _initializeChannel.then.then.then.then.catch (/home/ibm/.nvm/versions/node/v8.9.1/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:855:34)\n    at <anonymous>"}$
